config/routes.rb
Rails.application.routes.draw do
  get '/clients' => 'clients#index'
  get '/clients/new' => 'clients#new'
  get '/clients/:id' => 'clients#show', as: :client
  post '/clients' => 'clients#create'
  get '/clients/:id/edit' => 'clients#edit', as: :edit_client
  patch '/clients/:id' => 'clients#update'
  delete '/clients/:id' => 'clients#destroy', as: :delete_client

  get '/sessions/new' => 'sessions#new'
  get '/sessions/:id' => 'sessions#show', as: :session
  post '/sessions' => 'sessions#create'
  get '/sessions/:id/edit' => 'sessions#edit', as: :edit_session
  patch '/sessions/:id' => 'sessions#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord

  has_many :sessions

end

app/models/session.rb
class Session < ApplicationRecord

  belongs_to :client

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
    @sessions = @client.sessions
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update_attributes(client_params)
      redirect_to(:action => 'show', :id => @client.id)
    else
      render 'edit'
    end
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to '/clients'
    else
      render 'new'
    end
  end

  def destroy
    @client = Client.find(params[:id]).destroy
    redirect_to '/clients'
  end

  private
  def client_params
    params.require(:client).permit(:first_name, :last_name, :email, :phone, :injuries, :notes, :image)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def show
    @session = Session.find(params[:id])
  end

  def edit
    @session = Session.find(params[:id])
  end

  def update
    @session = Session.find(params[:id])
    if @session.update_attributes(session_params)
      redirect_to(:controller => 'clients', :action => 'show', :id => @session.client_id)
    else
      render 'edit'
    end
  end

  def new
    @session = Session.new
  end

  def create
    @session = Session.new(session_params)
    if @session.save
      redirect_to(:controller => 'clients', :action => 'show', :id => @session.client_id)
    else
      redirect_to(:controller => 'clients', :action => 'index')
    end
  end

  private
  def session_params
    params.require(:session).permit(:date, :location, :price, :notes, :client_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/clients/edit.html.erb
<%= form_for(@client) do |f| %>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_area :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_area :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_area :phone %>
  </div>
  <div class="field">
    <%= f.label :injuries %><br>
    <%= f.text_area :injuries %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </div>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/clients/index.html.erb
<div class="mini-header">
  This is my mini header
</div>

<div class="header">
  <div class="logo">
    <img src="http://icons.iconarchive.com/icons/iconarchive/red-orb-alphabet/256/Letter-Y-icon.png" alt="y-logo">
  </div>
  <div class="button-container">
    <%= link_to "/clients/new" do %>
      <div class="button">
        New Client
      </div>
    <% end %>
    <%= link_to "/sessions/new" do %>
      <div class="button">
        Log New Session
      </div>
    <% end %>
  </div>
</div>

<div class="body">
  <div class="client-container">
      <% @clients.order(:last_name).each do |t| %>
        <%= link_to client_path(t) do %>
          <div class="client">
            <div class="client-info">
              <img class="photo" src="<%= t.image %>"><br>
              <span class="name"><%= t.first_name %> <%= t.last_name %></span><br><br>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
</div>

<div class="footer">
  This is the footer
</div>

app/views/clients/new.html.erb
<%= form_for(@client) do |f| %>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_area :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_area :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_area :phone %>
  </div>
  <div class="field">
    <%= f.label :injuries %><br>
    <%= f.text_area :injuries %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </div>
  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/clients/show.html.erb
<div class="back">
  <a href="/clients">Back</a><br>
</div>

<div>
  <span>
    <h1><%= @client.first_name %> <%= @client.last_name %> <%= @client.id %> (<%= link_to "Edit", edit_client_path(@client) %>)</h1>
  </span>
  <div class="bio">
    <h3> Biographical Information</h3>
    Email: <%= @client.email %><br>
    Phone: <%= @client.phone %><br>
    injuries: <%= @client.injuries %><br>
    Notes: <%= @client.notes %><br>
  </div><br><br>

  <div class="session-row">
    <%= link_to 'Log New Session', "/sessions/new" %><br><br>
    <% @sessions.each do |d| %>
      <div class="card">
        <%= link_to "Edit", edit_session_path(d) %><br><br>
        Date: <%= d.date %><br>
        Location: <%= d.location %><br>
        Price: <%= d.price %><br>
        Notes: <%= d.notes %><br>
        Session ID: <%= d.id %><br>
      </div><br><br>
    <% end %>
  </div>
  <%= link_to "Delete this Client", delete_client_path(@client), method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sessions</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>